/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RatingEngineResult {
    id: string;
    overallScore: number;
    domainScores: RatingEngineDomainScores;
    overallStars: bigint;
    previousOverallStars: bigint;
    auditNotes: string;
    quarter: string;
    incentiveEligibility: RatingEngineIncentiveEligibility;
    calculatedAt: bigint;
    providerId: string;
    indicatorRatings: Array<RatingEngineIndicatorItem>;
}
export interface AuditLog {
    id: string;
    userRole: string;
    action: string;
    userId: string;
    timestamp: bigint;
    details: string;
    entityType: string;
}
export interface RatingEngineIncentiveEligibility {
    tier: string;
    screeningCompletion: number;
    estimatedPayment: number;
    eligible: boolean;
    improvementScore: number;
}
export interface IndicatorResult {
    id: string;
    trend: string;
    nationalBenchmark: number;
    quarter: string;
    rate: number;
    indicatorCode: string;
    indicatorName: string;
    dimension: string;
    providerId: string;
    quintileRank: bigint;
}
export interface NationalOverviewStats {
    dataQualityScore: number;
    screeningComplianceRate: number;
    totalProviders: bigint;
    highRiskFlagged: bigint;
    avgPreventiveScore: number;
    totalResidents: bigint;
    avgSafetyScore: number;
}
export interface HighRiskCohort {
    id: string;
    status: string;
    urgency: string;
    riskCriteria: string;
    flagDate: bigint;
    cohortSize: bigint;
    providerId: string;
}
export interface IndicatorSubmissionRecord {
    trend: string;
    domain: string;
    rate: number;
    indicatorCode: string;
    indicatorName: string;
    screeningCompletion: number;
    quintile: bigint;
    benchmark: number;
}
export interface RatingEngineDomainScores {
    safety: number;
    compliance: number;
    quality: number;
    staffing: number;
    experience: number;
    preventive: number;
}
export interface ScreeningWorkflow {
    id: string;
    status: string;
    completionTimeHours: number;
    dueDate: bigint;
    screeningType: string;
    providerId: string;
}
export interface RatingEngineIndicatorItem {
    trend: string;
    starRating: number;
    domain: string;
    trendAdjustment: number;
    rate: number;
    indicatorCode: string;
    indicatorName: string;
    quintile: bigint;
    benchmark: number;
}
export interface ProviderScorecard {
    id: string;
    experienceScore: number;
    overallScore: number;
    quarter: string;
    safetyScore: number;
    preventiveScore: number;
    providerId: string;
    equityScore: number;
    quintileRank: bigint;
}
export interface UserProfile {
    name: string;
}
export interface ProviderIndicatorSubmission {
    id: string;
    quarter: string;
    previousSafetyScore: number;
    submittedAt: bigint;
    indicators: Array<IndicatorSubmissionRecord>;
    screeningBundleCompletion: number;
    providerId: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAuditLogEntry(userId: string, userRole: string, action: string, entityType: string, details: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllHighRiskCohorts(): Promise<Array<HighRiskCohort>>;
    getAllRatingEngineResults(quarter: string): Promise<Array<RatingEngineResult>>;
    getAllScreeningWorkflows(): Promise<Array<ScreeningWorkflow>>;
    getAuditLogs(): Promise<Array<AuditLog>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHighRiskCohorts(providerId: string): Promise<Array<HighRiskCohort>>;
    getIndicatorResults(providerId: string, quarter: string): Promise<Array<IndicatorResult>>;
    getNationalOverviewStats(_quarter: string): Promise<NationalOverviewStats>;
    getProviderScorecardV2(providerId: string, quarter: string): Promise<RatingEngineResult | null>;
    getRatingEngineResult(providerId: string, quarter: string): Promise<RatingEngineResult | null>;
    getScorecardsByProvider(providerId: string): Promise<Array<ProviderScorecard>>;
    getScreeningWorkflows(providerId: string): Promise<Array<ScreeningWorkflow>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitIndicatorData(submission: ProviderIndicatorSubmission): Promise<RatingEngineResult>;
    updateScreeningStatus(workflowId: string, status: string): Promise<void>;
}
import type { RatingEngineResult as _RatingEngineResult, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAuditLogEntry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAuditLogEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAuditLogEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllHighRiskCohorts(): Promise<Array<HighRiskCohort>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHighRiskCohorts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHighRiskCohorts();
            return result;
        }
    }
    async getAllRatingEngineResults(arg0: string): Promise<Array<RatingEngineResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRatingEngineResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRatingEngineResults(arg0);
            return result;
        }
    }
    async getAllScreeningWorkflows(): Promise<Array<ScreeningWorkflow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllScreeningWorkflows();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllScreeningWorkflows();
            return result;
        }
    }
    async getAuditLogs(): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHighRiskCohorts(arg0: string): Promise<Array<HighRiskCohort>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHighRiskCohorts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHighRiskCohorts(arg0);
            return result;
        }
    }
    async getIndicatorResults(arg0: string, arg1: string): Promise<Array<IndicatorResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIndicatorResults(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIndicatorResults(arg0, arg1);
            return result;
        }
    }
    async getNationalOverviewStats(arg0: string): Promise<NationalOverviewStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getNationalOverviewStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNationalOverviewStats(arg0);
            return result;
        }
    }
    async getProviderScorecardV2(arg0: string, arg1: string): Promise<RatingEngineResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProviderScorecardV2(arg0, arg1);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProviderScorecardV2(arg0, arg1);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRatingEngineResult(arg0: string, arg1: string): Promise<RatingEngineResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingEngineResult(arg0, arg1);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingEngineResult(arg0, arg1);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScorecardsByProvider(arg0: string): Promise<Array<ProviderScorecard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScorecardsByProvider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScorecardsByProvider(arg0);
            return result;
        }
    }
    async getScreeningWorkflows(arg0: string): Promise<Array<ScreeningWorkflow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScreeningWorkflows(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScreeningWorkflows(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitIndicatorData(arg0: ProviderIndicatorSubmission): Promise<RatingEngineResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitIndicatorData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitIndicatorData(arg0);
            return result;
        }
    }
    async updateScreeningStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScreeningStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScreeningStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RatingEngineResult]): RatingEngineResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
